# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-16 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='login_reg.Message'),
            preserve_default=False,
        ),
    ]
